from typing import Protocol
from uuid import UUID

from ..models import Campaign, Conversation


class CampaignCatalog(Protocol):
    def create(self, campaign: Campaign) -> Campaign: ...
    def get(self, campaign_id: UUID) -> Campaign: ...
    def list_for_workspaces(self, workspace_ids: set[UUID]) -> list[Campaign]: ...


class ConversationCatalog(Protocol):
    def create(self, conversation: Conversation) -> Conversation: ...
    def list_for_campaign(self, campaign_id: UUID) -> list[Conversation]: ...
